//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoritmoGenetico.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgoritmoGenetico.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap aptidao {
            get {
                object obj = ResourceManager.GetObject("aptidao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avancar4 {
            get {
                object obj = ResourceManager.GetObject("avancar4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap avancarGrupo {
            get {
                object obj = ResourceManager.GetObject("avancarGrupo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap matriz {
            get {
                object obj = ResourceManager.GetObject("matriz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:
        ///1--
        ///2-70
        ///3-24
        ///4-69
        ///5-63
        ///6-58
        ///7-13
        ///8-96
        ///9-46
        ///
        ///2:
        ///1--
        ///2--
        ///3-29
        ///4-29
        ///5-65
        ///6-27
        ///7-97
        ///8-90
        ///9-53
        ///
        ///3:
        ///1--
        ///2--
        ///3--
        ///4-91
        ///5-30
        ///6-24
        ///7-93
        ///8-77
        ///9-58
        ///
        ///4:
        ///1--
        ///2--
        ///3--
        ///4--
        ///5-90
        ///6-35
        ///7-29
        ///8-94
        ///9-84
        ///
        ///
        ///5:
        ///1--
        ///2--
        ///3--
        ///4--
        ///5--
        ///6-45
        ///7-32
        ///8-22
        ///9-29
        ///
        ///6:
        ///1--
        ///2--
        ///3--
        ///4--
        ///5--
        ///6--
        ///7-48
        ///8-87
        ///9-29
        ///
        ///7:
        ///1--
        ///2--
        ///3--
        ///4--
        ///5--
        ///6--
        ///7--
        ///8-31
        ///9-31
        ///
        ///8:
        ///1--
        ///2--
        ///3--
        ///4--
        ///5--
        ///6--
        ///7--
        ///8--
        ///9-63
        ///
        ///9:
        ///1--
        ///2--
        ///3--
        ///4--
        ///5--
        ///6--
        ///7--
        ///8--
        ///9--.
        /// </summary>
        internal static string matrizDistancias {
            get {
                return ResourceManager.GetString("matrizDistancias", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mutacoes {
            get {
                object obj = ResourceManager.GetObject("mutacoes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reiniciar {
            get {
                object obj = ResourceManager.GetObject("reiniciar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resultado {
            get {
                object obj = ResourceManager.GetObject("resultado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
